import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.querySelector('#game'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(60,1,.1,120),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.shadowMap.enabled=true;scene.background=new THREE.Color(0x10151b);scene.fog=new THREE.Fog(0x10151b,15,48);
scene.add(new THREE.HemisphereLight(0xddeeff,0x24201a,2));const lamp=new THREE.DirectionalLight(0xffe1a8,2.4);lamp.position.set(5,12,4);lamp.castShadow=true;scene.add(lamp);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({color:0x38332e,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
function box(color,w,h,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.65,metalness:.15}));m.castShadow=m.receiveShadow=true;return m}
const player=box(0x4a78d8,.75,1.8,.75);player.position.set(0,.9,7);scene.add(player);
const machines=[{id:'machine_001',name:'1号機・青',x:-5,z:-3,color:0x315c96},{id:'machine_003',name:'3号機・赤',x:0,z:-3,color:0x9a3b38},{id:'machine_007',name:'7号機・金',x:5,z:-3,color:0xa87829}].map(d=>{const g=new THREE.Group();g.position.set(d.x,0,d.z);const body=box(d.color,1.8,3.4,.9);body.position.y=1.7;g.add(body);const screen=box(0x10151b,1.35,.75,.03);screen.position.set(0,2.35,-.48);g.add(screen);const light=box(0xffd66b,.18,.18,.05);light.position.set(0,1.1,-.5);g.add(light);g.userData=d;scene.add(g);return g});
const state={started:false,menu:false,money:1000,health:100,day:1,currentMachine:null};const keys=new Set();let yaw=Math.PI,pitch=-.28,dragging=false,last=performance.now();
const $=id=>document.getElementById(id);function hud(){ $('money').textContent=state.money; $('health').textContent=state.health; $('day').textContent=state.day; }
function reset(){state.started=false;state.menu=false;state.money=1000;state.health=100;state.currentMachine=null;$('machineMenu').classList.add('hidden');$('message').textContent='クリックで開始';hud();player.position.set(0,.9,7)}
function nearest(){let best=null,dist=Infinity;for(const m of machines){const d=player.position.distanceTo(m.position);if(d<dist){dist=d;best=m}}return dist<5?best:null}
const products=[['water_01','天然水',120],['coffee_01','ブラックコーヒー',150],['soda_01','炭酸飲料',130]];
function openMenu(machine){state.menu=true;state.currentMachine=machine;$('machineTitle').textContent=machine.userData.name;$('result').textContent='';$('products').replaceChildren(...products.map(([id,name,price],i)=>{const b=document.createElement('button');b.className='product';b.disabled=state.money<price;b.innerHTML=`<strong>${i+1}. ${name}</strong><small>¥${price}</small>`;b.onclick=()=>buy(id,name,price);return b}));$('restock').disabled=state.money>=120;$('machineMenu').classList.remove('hidden');$('prompt').textContent=''}
function closeMenu(){state.menu=false;state.currentMachine=null;$('machineMenu').classList.add('hidden')}
function buy(id,name,price){if(state.money<price)return;state.money-=price;const hit=Math.random()<.15;$('result').textContent=hit?`${name}を購入……先バレ！`: `${name}を購入した`;hud();document.querySelectorAll('.product').forEach((b,i)=>b.disabled=state.money<products[i][2]);$('restock').disabled=state.money>=120}
function restock(){state.day+=1;state.money+=1000;$('result').textContent=`DAY ${state.day}へ。所持金を補給した`;hud();openMenu(state.currentMachine)}
function forward(){const f=new THREE.Vector3();camera.getWorldDirection(f);f.y=0;return f.normalize()}
function update(dt){if(!state.started||state.menu)return;const f=forward(),r=new THREE.Vector3(f.z,0,-f.x),move=new THREE.Vector3();if(keys.has('KeyW')||keys.has('ArrowUp'))move.add(f);if(keys.has('KeyS')||keys.has('ArrowDown'))move.sub(f);if(keys.has('KeyD')||keys.has('ArrowRight'))move.add(r);if(keys.has('KeyA')||keys.has('ArrowLeft'))move.sub(r);if(move.lengthSq()){move.normalize();player.position.addScaledVector(move,4.2*dt);player.rotation.y=Math.atan2(move.x,move.z)}player.position.x=THREE.MathUtils.clamp(player.position.x,-14,14);player.position.z=THREE.MathUtils.clamp(player.position.z,-14,14);const m=nearest();$('prompt').textContent=m?`[E] ${m.userData.name} を調べる`:''}
function cameraUpdate(dt){const cp=Math.cos(pitch),desired=player.position.clone().add(new THREE.Vector3(Math.sin(yaw)*cp*7,3+Math.sin(-pitch)*7,Math.cos(yaw)*cp*7));camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(player.position.clone().add(new THREE.Vector3(0,1,0)))}
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);cameraUpdate(dt);renderer.render(scene,camera);requestAnimationFrame(frame)}
addEventListener('resize',resize);addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE'&&!state.menu){const m=nearest();if(m)openMenu(m)}if(e.code==='Escape'&&state.menu)closeMenu();if(e.code==='KeyR')reset()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('mousedown',e=>{if(!state.started){state.started=true;$('message').textContent='自販機を探せ';canvas.requestPointerLock?.();return}if(e.button===2)dragging=true});addEventListener('mouseup',()=>dragging=false);addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas||dragging){yaw-=e.movementX*.003;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0025,-.75,.25)}});$('closeMenu').onclick=closeMenu;$('restock').onclick=restock;resize();reset();requestAnimationFrame(frame);
